language:
    - php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*

before_script:
    - symfony/symfony:${SYMFONY_VERSION}
    - twig/extensions: "1.0.*@dev"
    - symfony/assetic-bundle: "2.3.*"
    - symfony/monolog-bundle: ">=2.3"
    - composer update --dev

script:
    - phpunit --coverage-text